<a href="https://colab.research.google.com/github/creamcheesesteak/test_visualization/blob/master/python_language.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
np.__version__

'1.19.5'

`__000__ `는 내장변수

In [55]:
def onehotcylinder(cylinders):
  if cylinders == 3:
    cylinder = np.array([1,0,0,0,0])
  elif cylinders == 4:
    cylinder = np.array([0,1,0,0,0])
  elif cylinders == 5:
    cylinder = np.array([0,0,1,0,0])
  elif cylinders == 6:
    cylinder = np.array([0,0,0,1,0])
  else : # 8
    cylinder = np.array([0,0,0,0,1])
  return cylinder


In [56]:
# input을 받음
displacement = 307.0
horsepower = 130.0
weight = 3504.0
accel = 12.0
cylinders = 8
origin = 1

# if cylinders = 8, origin = 1 --> onehot encoding
import numpy as np
if cylinders == 3:
  cylinder = np.array([1,0,0,0,0])
elif cylinders == 4:
  cylinder = np.array([0,1,0,0,0])
elif cylinders == 5:
  cylinder = np.array([0,0,1,0,0])
elif cylinders == 6:
  cylinder = np.array([0,0,0,1,0])
else : # 8
  cylinder = np.array([0,0,0,0,1])


x_continus = np.array([displacement, horsepower, weight, accel])
# cylinder = np.array([0,0,0,0,1,]) # 8
cylinder = onehotcylinder(cylinders)
org = np.array([1,0,0]) # 1




# x_continus = [[307.0, 130.0, 3504.0, 12.0]]

In [53]:
onehotcylinder(3), onehotcylinder(6)

(array([1, 0, 0, 0, 0]), array([0, 0, 0, 1, 0]))

In [54]:
cylinder

array([0, 0, 0, 0, 1])

In [18]:
type(x_continus), type(cylinder), type(org)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [19]:
# np.concatenate((a, b), axis=None)
result = np.concatenate((x_continus, cylinder, org), axis=None)
result.shape, result

((12,),
 array([3.070e+02, 1.300e+02, 3.504e+03, 1.200e+01, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 1.000e+00, 1.000e+00, 0.000e+00, 0.000e+00]))

In [21]:
# [[307.0, 130.0, 3504.0, 12.0, 0, 0, 0, 0, 1]]
# result.reshape(1, 12) 
result = result.reshape(-1,result.size)
result, result.shape, result.size

(array([[3.070e+02, 1.300e+02, 3.504e+03, 1.200e+01, 0.000e+00, 0.000e+00,
         0.000e+00, 0.000e+00, 1.000e+00, 1.000e+00, 0.000e+00, 0.000e+00]]),
 (1, 12),
 12)

In [ ]:
# input을 받음
displacement = 307.0
horsepower = 130.0
weight = 3504.0
accel = 12.0
cylinders = 8
origin = 1

# function 이해

In [22]:
21 + 14 

35

In [23]:
32 + 45

77

In [26]:
first = 21
second = 14
result = first + second
result

35

In [31]:
def sum(n1,n2):
  first = n1
  second = n2
  result = first + second
  return result

In [33]:
sum(32,34)

66

In [34]:
def mul(n1,n2,n3):
  first = n1
  second = n2
  third = n3
  result = first * second * third
  return result

In [35]:
mul(21,32,2)

1344

In [36]:
mul(31,63,41)

80073

In [38]:
def sum(f01, s02):
  first = f01
  second = s02
  result = first + second
  return result, second, first

In [39]:
_, r02, r03 = sum(21,564)

In [41]:
print(r02,r03)

564 21


In [48]:
# def differenceVars(*var01, **args02)
def diffparam(*var_list, **var_dict):
  print(var_dict)
  result01 = len(var_list)
  return result01

# * 이것은 변수인데 리스트라는 의미 ,**는 딕셔너리라는 의미



In [49]:
diffparam(1,2,3,a=2, b=3)



{'a': 2, 'b': 3}


3

In [50]:
diffparam(1,2,3,4,5,c=5, d=6, a=2, b=3)

{'c': 5, 'd': 6, 'a': 2, 'b': 3}


5